# networks: {tnet: {external: true}}

volumes:
  pgdata:

services:
  postgres:
    image: postgres:17.4
    restart: no
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PGDATA_PATH:-pgdata}:/var/lib/postgresql/data/pgdata
      # - /mnt/HC_Volume_102520323/loylvolume/pgdata:/var/lib/postgresql/data
    networks: [tnet-stage]

  redis:
    image: redis:8-alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-redis}"]
    restart: always
    networks: [tnet-stage]

networks:
  tnet-stage:
    external: true

