networks: {tnet: {external: true}}

services:
  postgres:
    image: postgres:17.4
    restart: always
    env_file: ./infra/env/${STACK:-prod}.env   # env
    volumes:
      - /mnt/HC_Volume_102520323/loylvolume/pgdata:/var/lib/postgresql/data
    networks: [tnet]

  redis:
    image: redis:8-alpine
    restart: always
    networks: [tnet]
