volumes:
  pgdata_dev:

networks:
  tnet-dev:
    driver: bridge

services:
  postgres:
    env_file: ./infra/env/dev.env
    volumes:
    - pgdata_dev:/var/lib/postgresql/data
    ports: ["5432:5432"]
    networks: [tnet-dev]

  redis:
    env_file: ./infra/env/dev.env
    ports: ["6379:6379"]
    networks: [tnet-dev]

  fastapi:
    env_file: ./infra/env/dev.env
    build:
      context: .
      dockerfile: containers/fastapi/Dockerfile
    ports: ["8000:8000"]
    networks: [tnet-dev]
  
  landing:
    build:
      context: .
      dockerfile: containers/landing/Dockerfile
    ports: ["80:80"]
    networks: [tnet-dev]
