volumes:
  pgdata_dev:

networks:
  tnet-dev:
    driver: bridge
    external: true

services:
  postgres:
    # env_file: ./infra/env/dev.env
    volumes:
    - pgdata_dev:/var/lib/postgresql/data
    ports: ["5432:5432"]
    networks: [tnet-dev]

  redis:
    # env_file: ./infra/env/dev.env
    ports: ["6379:6379"]
    networks: [tnet-dev]

  fastapi:
    # env_file: ./infra/env/dev.env
    build:
      context: .
      dockerfile: containers/fastapi/Dockerfile
    ports: ["8000:8000"]
    networks: [tnet-dev]
  
  anchor:
    build:
      context: .
      dockerfile: containers/anchor/Dockerfile
    command: >
      bash -c "
        avm use && 
        cd anchor &&
        anchor build &&
        anchor deploy --provider.cluster testnet
      "
    environment:
      - ANCHOR_WALLET=/root/.config/solana/id.json
      - SOLANA_URL=https://api.testnet.solana.com
    volumes:
      - ~/.config/solana:/root/.config/solana:ro
      - ./anchor:/anchor





  landing:
    build:
      context: .
      dockerfile: containers/landing/Dockerfile
    ports: ["80:80"]
    networks: [tnet-dev]
