volumes:
  pgdata_dev:


services:
  postgres:
    volumes:
    - pgdata_dev:/var/lib/postgresql/data
    ports: ["5432:5432"]

  redis:
    ports: ["6379:6379"]

  fastapi:
    build:
      context: .
      dockerfile: containers/fastapi/Dockerfile
    ports: ["8000:8000"]
    networks: [tnet]
  
  anchor:
    build:
      context: .
      dockerfile: containers/anchor/Dockerfile
    command: >
      bash -c "
        avm use && 
        cd anchor &&
        anchor build &&
        anchor deploy --provider.cluster testnet
      "
    environment:
      - ANCHOR_WALLET=/root/.config/solana/id.json
      - SOLANA_URL=https://api.testnet.solana.com
    volumes:
      - ~/.config/solana:/root/.config/solana:ro
      - ./anchor:/anchor





  landing:
    build:
      context: .
      dockerfile: containers/landing/Dockerfile
    ports: ["80:80"]
    networks: [tnet]