# networks: {tnet: {external: true}}

volumes:
  grafana_data:
  loki_data:


services:
  loki:
    image: grafana/loki:latest
    ports: [ "3100:3100" ]
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/config.yaml
      - loki_data:/loki
    networks: [tnet-stage, tnet-prod]

  promtail:
    image: grafana/promtail:latest
    user: root
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/promtail-config.yaml:/etc/promtail/config.yaml
    networks: [tnet-stage, tnet-prod]

  grafana:
    image: grafana/grafana:latest
    ports: [ "3000:3000" ]
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-loyladm}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_USER:-loyluser}
    volumes:
      - grafana_data:/var/lib/grafana
    networks: [tnet-stage, tnet-prod]

networks:
  tnet-stage:
    external: true
  tnet-prod:
    external: true

