services:
  postgres:
    env_file: ./infra/env/prod.env
    volumes:
      - /mnt/HC_Volume_102520323/loylvolume/pgdata:/var/lib/postgresql/data
    networks: [tnet-prod]
    depends_on: [redis]
  redis:
    env_file: ./infra/env/${STACK:-prod}.env
    networks: [tnet-prod] 
  landing:
    image: edvin3i/loyelto-landing:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.rule=Host(`loyel.to`)
      - traefik.http.routers.landing.entrypoints=websecure
      - traefik.http.routers.landing.tls.certresolver=le
    networks: [tnet-prod]

  fastapi:
    image: edvin3i/loyelto-fastapi:latest
    env_file: ./infra/env/prod.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`api.loyel.to`)
      - traefik.http.routers.fastapi.entrypoints=websecure
      - traefik.http.routers.fastapi.tls.certresolver=le
      - traefik.http.services.fastapi.loadbalancer.server.port=8000
    depends_on: [postgres, redis]
    networks: [tnet-prod]
