services:
  postgres:
    env_file: env/prod.env
    volumes:
      - /mnt/HC_Volume_102520323/loylvolume/pgdata-prod:/var/lib/postgresql/data
    networks: [tnet-prod]
    depends_on: [redis]
  redis:
    env_file: env/prod.env
    networks: [tnet-prod] 
  landing:
    image: edvin3i/loyelto-landing:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing-prod.rule=Host(`loyel.to`)
      - traefik.http.routers.landing-prod.entrypoints=websecure
      - traefik.http.routers.landing-prod.tls.certresolver=le
    networks: [tnet-prod]

  fastapi:
    image: edvin3i/loyelto-fastapi:latest
    env_file: env/prod.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi-prod.rule=Host(`api.loyel.to`)
      - traefik.http.routers.fastapi-prod.entrypoints=websecure
      - traefik.http.routers.fastapi-prod.tls.certresolver=le
      - traefik.http.services.fastapi-prod.loadbalancer.server.port=8000
    depends_on: [postgres, redis]
    networks: [tnet-prod]
