networks: {tnet: {external: true}}

services:
  landing:
    image: loyelto/landing:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.rule=Host(`loyel.to`)
      - traefik.http.routers.landing.entrypoints=websecure
      - traefik.http.routers.landing.tls.certresolver=le
    networks: [tnet]

  fastapi:
    image: loyelto/fastapi:latest
    env_file: ./infra/env/prod.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`api.loyel.to`)
      - traefik.http.routers.fastapi.entrypoints=websecure
      - traefik.http.routers.fastapi.tls.certresolver=le
      - traefik.http.services.fastapi.loadbalancer.server.port=8000
    depends_on: [postgres, redis]
    networks: [tnet]
