services:
  landing:
    image: loyelto/landing:staging
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.rule=Host(`stage.loyel.to`)
  fastapi:
    image: loyelto/fastapi:staging
    env_file: ./infra/env/stage.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`api.stage.loyel.to`)
