services:
  landing:
    image: edvin3i/loyelto:landing
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.rule=Host(`stage.loyel.to`)
  fastapi:
    image: edvin3i/loyelto:fastapi
    env_file: ./infra/env/stage.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`api.stage.loyel.to`)
