services:
  landing:
    image: edvin3i/loyelto-landing:stage
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.rule=Host(`stage.loyel.to`)
    networks: [tnet]
  fastapi:
    image: edvin3i/loyelto-fastapi:stage
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`api.stage.loyel.to`)
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-stage.loyel.to}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-loyelto_stage}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
      PRIVY_APP_ID: ${PRIVY_APP_ID}
      PRIVY_API_KEY: ${PRIVY_API_KEY}
      PRIVY_API_SECRET: ${PRIVY_API_SECRET}
      TREASURY_KEYPAIR: ${TREASURY_KEYPAIR}
      EXCHANGE_PROGRAM_ID: ${EXCHANGE_PROGRAM_ID:-"LoyL111111111111111111111111111111111111111"}
      EXCHANGE_IDL_PATH: ${EXCHANGE_IDL_PATH:-./dummy_idl.json}
      LOYL_TOKEN_PROGRAM_ID: ${LOYL_TOKEN_PROGRAM_ID:-}
      BIZ_FACTORY_PROGRAM_ID: ${BIZ_FACTORY_PROGRAM_ID:-}
    networks: [tnet]
  anchor:
    image: edvin3i/loyelto-anchor:stage
    command: >
      bash -c "
        avm use 0.29.0 &&
        cd /anchor &&
        anchor build &&
        anchor deploy --provider.cluster testnet
      "
    environment:
      - ANCHOR_WALLET=/root/.config/solana/id.json
      - SOLANA_URL=https://api.testnet.solana.com
    volumes:
      - ~/.config/solana:/root/.config/solana:ro
      - ../srcs/backend/anchor:/anchor
    networks: [tnet]

  worker:
    build: ../containers/worker
    depends_on:
      - redis
      - fastapi
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/1
    networks: [tnet]

  beat:
    build: ../containers/beat
    depends_on:
      - redis
      - fastapi
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/1
    networks: [tnet]