"""fix fk in busines reviews

Revision ID: 7dacb2d667c5
Revises: 0002_owner_pubkey
Create Date: 2025-05-30 03:04:51.831289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dacb2d667c5'
down_revision: Union[str, None] = '0002_owner_pubkey'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=2), nullable=False, comment='Score from 1.00 to 5.00'),
    sa.Column('review_text', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='check_score_range'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('voucher_mint_txs')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_owner_pubkey'), ['owner_pubkey'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_owner_pubkey'))

    op.create_table('voucher_mint_txs',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('template_id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('asset_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['voucher_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('business_reviews')
    # ### end Alembic commands ###
