[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
loyl_settlement = "47RVB2NnGEYXdSvxxN7DfLFk69FvpJemvhH4rxLnjE4s"
exchange = "uMhywp8T3MGLrXPgaTnX7HQjNCT6Cv9tp9pfZ2S7WBp"
loyl_token = "3kzE3Xvgzi9PurL9cjRU7t9twHLYZUhaVv2AVmLXqbxm"

[programs.localnet]
loyl_settlement = "47RVB2NnGEYXdSvxxN7DfLFk69FvpJemvhH4rxLnjE4s"
exchange = "uMhywp8T3MGLrXPgaTnX7HQjNCT6Cv9tp9pfZ2S7WBp"
loyl_token = "3kzE3Xvgzi9PurL9cjRU7t9twHLYZUhaVv2AVmLXqbxm"

[programs.testnet]
loyl_settlement = "47RVB2NnGEYXdSvxxN7DfLFk69FvpJemvhH4rxLnjE4s"
exchange = "uMhywp8T3MGLrXPgaTnX7HQjNCT6Cv9tp9pfZ2S7WBp"
loyl_token = "3kzE3Xvgzi9PurL9cjRU7t9twHLYZUhaVv2AVmLXqbxm"




[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.solana.com"
wallet = "/Users/edvin/.config/solana/id.json"

[workspace]
members = ["programs/exchange", "programs/loyl_settlement", "programs/loyl_token"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
