[toolchain]
package_manager = "yarn"

[features]
resolution = true
idl-build = ["anchor-spl/idl-build"]
skip-lint   = false

[programs.localnet]
exchange = "F9JP31siPUtWkS5GKEZPt4dvgqbZGZ6Uukyk5NMZ9kAz"

[programs.devnet]
exchange = "F9JP31siPUtWkS5GKEZPt4dvgqbZGZ6Uukyk5NMZ9kAz"

[registry]
url = "https://api.apr.dev"

[workspace]
members = ["programs/exchange"]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
