/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shops_list` | `/shops_list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/show_qr` | `/show_qr`; params?: Router.UnknownInputParams; } | { pathname: `/utils/business_profile`; params?: Router.UnknownInputParams; } | { pathname: `/utils/styles`; params?: Router.UnknownInputParams; } | { pathname: `/utils/styles_shops_list`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/business/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/shops_list` | `/shops_list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/show_qr` | `/show_qr`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/business_profile`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/styles_shops_list`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/business/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/shops_list${`?${string}` | `#${string}` | ''}` | `/shops_list${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/show_qr${`?${string}` | `#${string}` | ''}` | `/show_qr${`?${string}` | `#${string}` | ''}` | `/utils/business_profile${`?${string}` | `#${string}` | ''}` | `/utils/styles${`?${string}` | `#${string}` | ''}` | `/utils/styles_shops_list${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shops_list` | `/shops_list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/show_qr` | `/show_qr`; params?: Router.UnknownInputParams; } | { pathname: `/utils/business_profile`; params?: Router.UnknownInputParams; } | { pathname: `/utils/styles`; params?: Router.UnknownInputParams; } | { pathname: `/utils/styles_shops_list`; params?: Router.UnknownInputParams; } | `/+not-found` | `/business/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/business/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
