server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: docker
#     static_configs:
#       - targets: [localhost]
#         labels:
#           job: docker
#           env: stage
#           compose_project: loyelto
#           __path__: /var/lib/docker/containers/*/*.log



scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "/(.+)"
        target_label: container
      - source_labels: [__meta_docker_container_label_env]
        target_label: env
      - source_labels: [__meta_docker_container_label_project]
        target_label: project
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project


  # - job_name: varlogs
  #   static_configs:
  #     - targets: [localhost]
  #       labels:
  #         job: varlogs
  #         __path__: /var/log/*log