name: Docker CI/CD

on:
  push:
    branches: [ master ]          # prod
  pull_request:
    branches: [ master ]          # staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: containers/landing/Dockerfile
            image: loyelto/landing
          - dir: containers/fastapi/Dockerfile
            image: loyelto/fastapi

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dir }}
          push: true
          tags: |
            ${{ matrix.image }}:${{ github.event_name == 'push' && 'latest' || 'staging' }}
            ${{ matrix.image }}:${{ github.sha }}
  deploy-prod:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Start on VPS
        uses: appleboy/ssh-action@v1
        with:
          host:   ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:   ${{ secrets.SSH_KEY }}
          script: |
            cd /home/loylapp/loyelto
            git pull --ff-only
            docker pull loyelto/landing:latest
            docker pull loyelto/api:latest
            make up-prod
            docker image prune -f
