name: Docker CI/CD

on:
  push:
    branches: [ master, stage ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: containers/landing/Dockerfile
            image: edvin3i/loyelto-landing
          - dir: containers/fastapi/Dockerfile
            image: edvin3i/loyelto-fastapi
          - dir: containers/anchor/Dockerfile
            image: edvin3i/loyelto-anchor

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=stage" >> $GITHUB_ENV
          fi
      
      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dir }}
          push: true
          tags: |
            ${{ matrix.image }}:${{ env.IMAGE_TAG }}
            ${{ matrix.image }}:${{ github.sha }}

  deploy:
    needs: build
    if: github.event_name == 'master' || github.ref_name == 'stage'
    runs-on: ubuntu-latest
    steps:
      - name: Set image tag
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "STACK=prod" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=stage" >> $GITHUB_ENV
            echo "STACK=stage" >> $GITHUB_ENV
          fi
      
      - name: Start on VPS
        uses: appleboy/ssh-action@v1
        with:
          host:   ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:   ${{ secrets.SSH_KEY }}
          script: |
            cd /home/loylapp/loyelto
            git pull --ff-only
            docker pull edvin3i/loyelto-landing:${{ env.IMAGE_TAG }}
            docker pull edvin3i/loyelto-fastapi:${{ env.IMAGE_TAG }}
            docker pull edvin3i/loyelto-anchor:${{ env.IMAGE_TAG }}
            make up-${{ env.STACK }}
            docker image prune -f

